### PR TITLE
Add support for custom name, description at checkout. And receipt_thank_you_note.

### PR DESCRIPTION
**Pull request by UrosCodes**
This will add support for custom name and decription during the checkout by providing the $productName and $description.

name - A custom name for the product
description - A custom description for the product
receipt_thank_you_note - A custom thank you note to use for the order receipt email

And still didnt get to know how to make this receipt_thank_you_note work.
Do you have any suggestion how make this work?

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks! I adjusted this a bit

**Comment by UrosCodes** [comment]
Thank you for adding this.

It seems that **->withthankYouNote** is **not working** for some reason.
I use test mode and it always throw default message and not custom message from receipt_thank_you_note

Can you check why it is not working?

**Comment by driesvints** [comment]
@UrosCodes you might want to reach out to lemon Squeezy support for that because afaik we’re using the key as intended in the api docs

**Comment by chimit** [comment]
I believe the `withThankYouNote()` method works but only in invoices. It would be nice if we had a way to customize the thank you message in the modal after successful payment.

**Comment by UrosCodes** [comment]
> I believe the `withThankYouNote()` method works but only in invoices. It would be nice if we had a way to customize the thank you message in the modal after successful payment.

You can do it directly here:
https://docs.lemonsqueezy.com/help/checkout/customizing-confirmation-modal

**Comment by chimit** [comment]
Yes, but it would be convenient to define it from code. E.g. for localization.

**Pull request merged**
